sudo: required
dist: trusty

language: cpp

os: linux

compiler:
    - gcc

addons:
  apt:
    packages:
      - libsnappy-dev
      - liblz4-dev

cache:
    - ccache
    - apt

before_install:
    - wget https://raw.githubusercontent.com/xiaomi/pegasus-common/master/build-depends.tar.gz
    - tar xf build-depends.tar.gz
    - cd packages
    - ls | xargs sudo dpkg -i --force-depends
    - cd ..

install:
    - wget https://github.com/facebook/zstd/archive/v1.3.7.zip; unzip v1.3.7; cd zstd-1.3.7;
    - mkdir cmake-build; cd cmake-build; cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DZSTD_BUILD_PROGRAMS=OFF ../build/cmake; sudo make install -j8;
    - cd ../..

before_script:
    - cd rdsn/thirdparty
    - wget https://raw.githubusercontent.com/xiaomi/pegasus-common/master/pegasus-thirdparty-prebuild.tar.gz
    - tar xf pegasus-thirdparty-prebuild.tar.gz
    - rm -rf pegasus-thirdparty-prebuild.tar.gz
    - cd ../..
    - ulimit -c unlimited -S

script:
    - ./run.sh build && ./run.sh test

notifications:
    email: false
